CREATE TABLE TBL_MEMBER(
ID NUMBER(4) PRIMARY KEY,
PW NUMBER(10) NOT NULL, 
NAME VARCHAR2(50) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE TBL_EXIT_MEMBER(
EXIT_ID NUMBER(4),
EXIT_NAME VARCHAR2(50) NOT NULL,
EXIT_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_EXIT_MEMBER;


/
CREATE OR REPLACE TRIGGER T
AFTER DELETE ON TBL_MEMBER
FOR EACH ROW
BEGIN
INSERT INTO TBL_EXIT_MEMBER(EXIT_ID, EXIT_NAME, EXIT_DATE)
VALUES(:OLD.ID, :OLD.NAME, sysdate);
END;
/
commit;

DELETE FROM TBL_MEMBER;
DELETE FROM TBL_EXIT_MEMBER;
DROP TRIGGER T;





