CREATE TABLE SHOP_PRODUCT(
PROD_ID NUMBER(4) PRIMARY KEY,   --상품번호
PROD_NAME VARCHAR2(50) NOT NULL, --상품명
CATEGORY VARCHAR2(20),           --카테고리
PRICE NUMBER(10) CHECK (PRICE > 0), --단가(0보다 커야함)
STOCK NUMBER(5) ,                --재고수량
REG_DATE DATE DEFAULT SYSDATE    --등록일
);

INSERT INTO SHOP_PRODUCT(PROD_ID, PROD_NAME, CATEGORY, PRICE, STOCK, REG_DATE)
VALUES(1, 'S냉장고', '가전', 1000000, 10, '2026-04-28');
INSERT INTO SHOP_PRODUCT
VALUES(2, '에어컨', '가전', 1200000, 5, '2026-04-28');
INSERT INTO SHOP_PRODUCT
VALUES(3, '쇼파', '생활', 50000, 20, '2026-04-28');
INSERT INTO SHOP_PRODUCT
VALUES(4, '테이블', '생활', 100000, 20, '2026-04-28');


SELECT * FROM SHOP_PRODUCT;

--<2-1>
SELECT PROD_NAME AS "상품명" ,CATEGORY AS "카테고리", PRICE AS "단가"
FROM SHOP_PRODUCT
ORDER BY PRICE DESC;

--<2-2>
SELECT  CATEGORY AS "카테고리", AVG(PRICE) AS "평균단가"
FROM SHOP_PRODUCT
GROUP BY CATEGORY
HAVING AVG(PRICE) >= 500000;

--<2-3>
SELECT PROD_NAME AS "상품명", PRICE AS "단가"
FROM SHOP_PRODUCT
WHERE PRICE > (SELECT AVG(PRICE) FROM SHOP_PRODUCT);

--<2-4>
UPDATE SHOP_PRODUCT
SET PRICE = (PRICE *0.1)+PRICE
WHERE CATEGORY = '가전' AND STOCK <10;

--<2-5>
SELECT PROD_ID AS "상품번호", PROD_NAME AS "상품명", CATEGORY AS "카테고리", PRICE AS "단가", STOCK AS "재고수량", REG_DATE AS "등록일" 
FROM SHOP_PRODUCT
WHERE PROD_NAME LIKE 'S%' OR CATEGORY = '생활';

--<3>

--<4>
CREATE TABLE DEL_LOG (
P_ID NUMBER(4),
DEL_DATE DATE DEFAULT SYSDATE
);
/
CREATE OR REPLACE TRIGGER T
AFTER DELETE ON SHOP_PRODUCT
FOR EACH ROW
BEGIN
INSERT INTO DEL_LOG(PROD_ID, REG_DATE)
VALUES(:OLD.PROD_ID, sysdate);
END;
/

SELECT * FROM DEL_LOG; //트리거 테이블
SELECT * FROM SHOP_PRODUCT; 




